// Real society member data extracted from "society members.xlsx"
// SHIVKRUPASAGAR CO OP HOUSING SOCIETY LTD

export interface SocietyMember {
  uid: string;
  name: string;
  email: string;
  flatNumber: string;
  wing: string;
  phone: string;
  role: "chairman" | "secretary" | "treasurer" | "member";
  status: "Active" | "Inactive";
  joinedDate: string;
}

export const societyMembers: SocietyMember[] = [
  {
    uid: "member-001",
    name: "Pradnya S. Abhyankar",
    email: "pradnya.s.abhyankar@society.com",
    flatNumber: "001",
    wing: "Ground",
    phone: "+91 9XXXXXXXXX",
    role: "chairman",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-002",
    name: "Pradnya S. Abhyankar",
    email: "pradnya.s.abhyankar@society.com",
    flatNumber: "002",
    wing: "Ground",
    phone: "+91 9XXXXXXXXX",
    role: "secretary",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-003",
    name: "Rajesh G. Shingare",
    email: "rajesh.g.shingare@society.com",
    flatNumber: "003",
    wing: "Ground",
    phone: "+91 9XXXXXXXXX",
    role: "treasurer",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-004",
    name: "M. Padmanabhan",
    email: "m.padmanabhan@society.com",
    flatNumber: "004",
    wing: "Ground",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-005",
    name: "Rajan D Khedekar / Prashant D Khedekar",
    email: "rajan.d.khedekar@society.com",
    flatNumber: "005",
    wing: "Ground",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-006",
    name: "Varsha Sanjiv Joshi",
    email: "varsha.sanjiv.joshi@society.com",
    flatNumber: "006",
    wing: "Ground",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-007",
    name: "Sanjay D. Gala",
    email: "sanjay.d.gala@society.com",
    flatNumber: "101",
    wing: "1st Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-008",
    name: "U.J. Wagle",
    email: "u.j.wagle@society.com",
    flatNumber: "102",
    wing: "1st Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-009",
    name: "S.J.Desai",
    email: "s.j.desai@society.com",
    flatNumber: "103",
    wing: "1st Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-010",
    name: "Mahesh D. Bokare",
    email: "mahesh.d.bokare@society.com",
    flatNumber: "104",
    wing: "1st Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-011",
    name: "Dr. A.B. Malagi",
    email: "dr.a.b.malagi@society.com",
    flatNumber: "105/106",
    wing: "",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-012",
    name: "Sampada Chougule",
    email: "sampada.chougule@society.com",
    flatNumber: "201",
    wing: "2nd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-013",
    name: "P.N. Rane",
    email: "p.n.rane@society.com",
    flatNumber: "202",
    wing: "2nd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-014",
    name: "T.D. Mane",
    email: "t.d.mane@society.com",
    flatNumber: "203",
    wing: "2nd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-015",
    name: "Kedar M. Patankar",
    email: "kedar.m.patankar@society.com",
    flatNumber: "204",
    wing: "2nd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-016",
    name: "Santosh Gholap",
    email: "santosh.gholap@society.com",
    flatNumber: "205",
    wing: "2nd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-017",
    name: "Sameer Dharamshi",
    email: "sameer.dharamshi@society.com",
    flatNumber: "206",
    wing: "2nd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-018",
    name: "D.D.Patil",
    email: "d.d.patil@society.com",
    flatNumber: "301",
    wing: "3rd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-019",
    name: "S.K. Mallaiya",
    email: "s.k.mallaiya@society.com",
    flatNumber: "302",
    wing: "3rd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-020",
    name: "S.M. Patankar",
    email: "s.m.patankar@society.com",
    flatNumber: "303",
    wing: "3rd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-021",
    name: "M.A. Ramnathkar",
    email: "m.a.ramnathkar@society.com",
    flatNumber: "304",
    wing: "3rd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-022",
    name: "A.A. Thakkar",
    email: "a.a.thakkar@society.com",
    flatNumber: "305",
    wing: "3rd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-023",
    name: "Nirmal A. Darji",
    email: "nirmal.a.darji@society.com",
    flatNumber: "306",
    wing: "3rd Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-024",
    name: "H.T. Gawade",
    email: "h.t.gawade@society.com",
    flatNumber: "401",
    wing: "4th Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-025",
    name: "Pravin S. Nipunge",
    email: "pravin.s.nipunge@society.com",
    flatNumber: "402",
    wing: "4th Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-026",
    name: "Shirish L. Barate",
    email: "shirish.l.barate@society.com",
    flatNumber: "403",
    wing: "4th Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-027",
    name: "Mangesh Bhosale",
    email: "mangesh.bhosale@society.com",
    flatNumber: "404",
    wing: "4th Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-028",
    name: "S.S. Gajendragadkar",
    email: "s.s.gajendragadkar@society.com",
    flatNumber: "405",
    wing: "4th Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  },
  {
    uid: "member-029",
    name: "Sachin R. Mahajan",
    email: "sachin.r.mahajan@society.com",
    flatNumber: "406",
    wing: "4th Floor",
    phone: "+91 9XXXXXXXXX",
    role: "member",
    status: "Active",
    joinedDate: "2024-04-01T00:00:00.000Z",
  }
];
