// Generated Real Society Data
class RealSocietyData {
  static final List<Map<String, dynamic>> users = [
    {
      'uid': 'admin_chairman',
      'name': 'System Chairman',
      'email': 'chairman@society.com',
      'password': '123456',
      'phone': '9100000000',
      'flatNumber': 'ADMIN',
      'role': 'chairman',
      'status': 'Active',
      'openingBalance': 0, 'sinkingFund': 0, 'maintenanceAmount': 0, 'municipalTax': 0, 'noc': 0, 'parkingCharges': 0, 'delayCharges': 0, 'buildingFund': 0, 'roomTransferFees': 0, 'totalReceivable': 0, 'totalReceived': 0, 'closingBalance': 0, 'fixedMonthlyCharges': 0, 'annualCharges': 0, 'variableCharges': 0,
    },
    {
      'uid': 'admin_secretary',
      'name': 'System Secretary',
      'email': 'secretary@society.com',
      'password': '123456',
      'phone': '9100000000',
      'flatNumber': 'ADMIN',
      'role': 'secretary',
      'status': 'Active',
      'openingBalance': 0, 'sinkingFund': 0, 'maintenanceAmount': 0, 'municipalTax': 0, 'noc': 0, 'parkingCharges': 0, 'delayCharges': 0, 'buildingFund': 0, 'roomTransferFees': 0, 'totalReceivable': 0, 'totalReceived': 0, 'closingBalance': 0, 'fixedMonthlyCharges': 0, 'annualCharges': 0, 'variableCharges': 0,
    },
    {
      'uid': 'admin_treasurer',
      'name': 'System Treasurer',
      'email': 'treasurer@society.com',
      'password': '123456',
      'phone': '9100000000',
      'flatNumber': 'ADMIN',
      'role': 'treasurer',
      'status': 'Active',
      'openingBalance': 0, 'sinkingFund': 0, 'maintenanceAmount': 0, 'municipalTax': 0, 'noc': 0, 'parkingCharges': 0, 'delayCharges': 0, 'buildingFund': 0, 'roomTransferFees': 0, 'totalReceivable': 0, 'totalReceived': 0, 'closingBalance': 0, 'fixedMonthlyCharges': 0, 'annualCharges': 0, 'variableCharges': 0,
    },
    {
      'uid': 'member_1',
      'name': 'Pradnya S. Abhyankar',
      'email': 'pradnyasabhyankar@gmail.com',
      'password': '123456',
      'phone': '9100000000',
      'flatNumber': '001',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 3865,
      'sinkingFund': 384,
      'maintenanceAmount': 4560,
      'municipalTax': 2880,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1880,
      'roomTransferFees': 0,
      'totalReceivable': 13569,
      'totalReceived': 11000,
      'closingBalance': 2569,
      'fixedMonthlyCharges': 652,
      'annualCharges': 1880,
      'variableCharges': 0,
    },
    {
      'uid': 'member_2',
      'name': 'Pradnya S. Abhyankar',
      'email': 'pradnyasabhyankar2@gmail.com',
      'password': '123456',
      'phone': '9100000000',
      'flatNumber': '002',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 1735,
      'sinkingFund': 288,
      'maintenanceAmount': 4560,
      'municipalTax': 2388,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1500,
      'roomTransferFees': 0,
      'totalReceivable': 10471,
      'totalReceived': 9000,
      'closingBalance': 1471,
      'fixedMonthlyCharges': 603,
      'annualCharges': 1500,
      'variableCharges': 0,
    },
    {
      'uid': 'member_3',
      'name': 'Rajesh G. Shingare',
      'email': 'rajeshgshingare@gmail.com',
      'password': '123456',
      'phone': '9100000000',
      'flatNumber': '003',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 150,
      'sinkingFund': 300,
      'maintenanceAmount': 4560,
      'municipalTax': 2040,
      'noc': 3600,
      'parkingCharges': 0,
      'delayCharges': 25,
      'buildingFund': 1400,
      'roomTransferFees': 0,
      'totalReceivable': 12075,
      'totalReceived': 12000,
      'closingBalance': 75,
      'fixedMonthlyCharges': 575,
      'annualCharges': 1400,
      'variableCharges': 3625,
    },
    {
      'uid': 'member_4',
      'name': 'M. Padmanabhan',
      'email': 'mpadmanabhan@gmail.com',
      'password': 'm123',
      'phone': '9100000000',
      'flatNumber': '004',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 0,
      'sinkingFund': 360,
      'maintenanceAmount': 4560,
      'municipalTax': 2880,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1900,
      'roomTransferFees': 0,
      'totalReceivable': 9700,
      'totalReceived': 9700,
      'closingBalance': 0,
      'fixedMonthlyCharges': 650,
      'annualCharges': 1900,
      'variableCharges': 0,
    },
    {
      'uid': 'member_5',
      'name': 'Rajan D Khedekar Prashant D Khedekar',
      'email': 'rajankhedekar@gmail.com',
      'password': 'rajan123',
      'phone': '9100000000',
      'flatNumber': '005',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 0,
      'sinkingFund': 264,
      'maintenanceAmount': 4560,
      'municipalTax': 1932,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1360,
      'roomTransferFees': 0,
      'totalReceivable': 8116,
      'totalReceived': 8116,
      'closingBalance': 0,
      'fixedMonthlyCharges': 563,
      'annualCharges': 1360,
      'variableCharges': 0,
    },
    {
      'uid': 'member_6',
      'name': 'Varsha Sanjiv Joshi',
      'email': 'varshajoshi@gmail.com',
      'password': 'varsha123',
      'phone': '9100000000',
      'flatNumber': '006',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 0,
      'sinkingFund': 336,
      'maintenanceAmount': 4560,
      'municipalTax': 3504,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 25,
      'buildingFund': 2140,
      'roomTransferFees': 0,
      'totalReceivable': 10565,
      'totalReceived': 10565,
      'closingBalance': 0,
      'fixedMonthlyCharges': 700,
      'annualCharges': 2140,
      'variableCharges': 25,
    },
    {
      'uid': 'member_7',
      'name': 'Sanjay D. Gala',
      'email': 'sanjaygala@gmail.com',
      'password': 'sanjay123',
      'phone': '9100000000',
      'flatNumber': '101',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 0,
      'sinkingFund': 300,
      'maintenanceAmount': 4560,
      'municipalTax': 2880,
      'noc': 0,
      'parkingCharges': 300,
      'delayCharges': 0,
      'buildingFund': 1880,
      'roomTransferFees': 0,
      'totalReceivable': 9920,
      'totalReceived': 9920,
      'closingBalance': 0,
      'fixedMonthlyCharges': 645,
      'annualCharges': 1880,
      'variableCharges': 300,
    },
    {
      'uid': 'member_8',
      'name': 'U.J. Wagle',
      'email': 'ujwagle@gmail.com',
      'password': 'uj123',
      'phone': '9100000000',
      'flatNumber': '102',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 1200,
      'sinkingFund': 288,
      'maintenanceAmount': 4560,
      'municipalTax': 2388,
      'noc': 3600,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1500,
      'roomTransferFees': 0,
      'totalReceivable': 13536,
      'totalReceived': 13536,
      'closingBalance': 0,
      'fixedMonthlyCharges': 603,
      'annualCharges': 1500,
      'variableCharges': 3600,
    },
    {
      'uid': 'member_9',
      'name': 'S.J.Desai',
      'email': 'sjdesaisjdesai@gmail.com',
      'password': 'sjdesai123',
      'phone': '9100000000',
      'flatNumber': '103',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 1594,
      'sinkingFund': 504,
      'maintenanceAmount': 4560,
      'municipalTax': 2040,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1560,
      'roomTransferFees': 0,
      'totalReceivable': 10258,
      'totalReceived': 8664,
      'closingBalance': 1594,
      'fixedMonthlyCharges': 592,
      'annualCharges': 1560,
      'variableCharges': 0,
    },
    {
      'uid': 'member_10',
      'name': 'Mahesh D. Bokare',
      'email': 'maheshbokare@gmail.com',
      'password': 'mahesh123',
      'phone': '9100000000',
      'flatNumber': '104',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 3775,
      'sinkingFund': 360,
      'maintenanceAmount': 4560,
      'municipalTax': 2880,
      'noc': 0,
      'parkingCharges': 300,
      'delayCharges': 0,
      'buildingFund': 1900,
      'roomTransferFees': 0,
      'totalReceivable': 13775,
      'totalReceived': 10000,
      'closingBalance': 3775,
      'fixedMonthlyCharges': 650,
      'annualCharges': 1900,
      'variableCharges': 300,
    },
    {
      'uid': 'member_11',
      'name': 'Dr. A.B. Malagi',
      'email': 'drmalagi@gmail.com',
      'password': 'dr123',
      'phone': '9100000000',
      'flatNumber': '105/106',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 20,
      'sinkingFund': 552,
      'maintenanceAmount': 5520,
      'municipalTax': 5568,
      'noc': 0,
      'parkingCharges': 300,
      'delayCharges': 0,
      'buildingFund': 3500,
      'roomTransferFees': 0,
      'totalReceivable': 15460,
      'totalReceived': 15460,
      'closingBalance': 0,
      'fixedMonthlyCharges': 970,
      'annualCharges': 3500,
      'variableCharges': 300,
    },
    {
      'uid': 'member_12',
      'name': 'Sampada Chougule',
      'email': 'sampadachougule@gmail.com',
      'password': 'sampada123',
      'phone': '9100000000',
      'flatNumber': '201',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 0,
      'sinkingFund': 300,
      'maintenanceAmount': 4560,
      'municipalTax': 2880,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1880,
      'roomTransferFees': 25000,
      'totalReceivable': 34620,
      'totalReceived': 32740,
      'closingBalance': 1880,
      'fixedMonthlyCharges': 645,
      'annualCharges': 1880,
      'variableCharges': 25000,
    },
    {
      'uid': 'member_13',
      'name': 'P.N. Rane',
      'email': 'pnrane@gmail.com',
      'password': 'pn123',
      'phone': '9100000000',
      'flatNumber': '202',
      'role': 'member',
      'status': 'Active',
      'openingBalance': -1809,
      'sinkingFund': 288,
      'maintenanceAmount': 4560,
      'municipalTax': 2388,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1500,
      'roomTransferFees': 0,
      'totalReceivable': 6927,
      'totalReceived': 3500,
      'closingBalance': 3427,
      'fixedMonthlyCharges': 603,
      'annualCharges': 1500,
      'variableCharges': 0,
    },
    {
      'uid': 'member_14',
      'name': 'T.D. Mane',
      'email': 'tdmane@gmail.com',
      'password': 'td123',
      'phone': '9100000000',
      'flatNumber': '203',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 125,
      'sinkingFund': 252,
      'maintenanceAmount': 4560,
      'municipalTax': 2040,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1560,
      'roomTransferFees': 0,
      'totalReceivable': 8537,
      'totalReceived': 8462,
      'closingBalance': 75,
      'fixedMonthlyCharges': 571,
      'annualCharges': 1560,
      'variableCharges': 0,
    },
    {
      'uid': 'member_15',
      'name': 'Kedar M. Patankar',
      'email': 'kedarpatankar@gmail.com',
      'password': 'kedar123',
      'phone': '9100000000',
      'flatNumber': '204',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 18175,
      'sinkingFund': 300,
      'maintenanceAmount': 4560,
      'municipalTax': 2784,
      'noc': 4200,
      'parkingCharges': 300,
      'delayCharges': 0,
      'buildingFund': 1900,
      'roomTransferFees': 0,
      'totalReceivable': 32219,
      'totalReceived': 9668,
      'closingBalance': 22551,
      'fixedMonthlyCharges': 637,
      'annualCharges': 1900,
      'variableCharges': 4500,
    },
    {
      'uid': 'member_16',
      'name': 'Santosh Gholap',
      'email': 'santoshgholap@gmail.com',
      'password': 'santosh123',
      'phone': '9100000000',
      'flatNumber': '205',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 0,
      'sinkingFund': 264,
      'maintenanceAmount': 4560,
      'municipalTax': 1932,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 150,
      'buildingFund': 1360,
      'roomTransferFees': 15000,
      'totalReceivable': 23266,
      'totalReceived': 23266,
      'closingBalance': 0,
      'fixedMonthlyCharges': 563,
      'annualCharges': 1360,
      'variableCharges': 15150,
    },
    {
      'uid': 'member_17',
      'name': 'Sameer Dharamshi',
      'email': 'sameerdharamshi@gmail.com',
      'password': 'sameer123',
      'phone': '9100000000',
      'flatNumber': '206',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 700,
      'sinkingFund': 336,
      'maintenanceAmount': 4560,
      'municipalTax': 3504,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 25,
      'buildingFund': 2140,
      'roomTransferFees': 0,
      'totalReceivable': 11265,
      'totalReceived': 11265,
      'closingBalance': 0,
      'fixedMonthlyCharges': 700,
      'annualCharges': 2140,
      'variableCharges': 25,
    },
    {
      'uid': 'member_18',
      'name': 'D.D.Patil',
      'email': 'ddpatilddpatil@gmail.com',
      'password': 'ddpatil123',
      'phone': '9100000000',
      'flatNumber': '301',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 4280,
      'sinkingFund': 300,
      'maintenanceAmount': 4560,
      'municipalTax': 2880,
      'noc': 4200,
      'parkingCharges': 0,
      'delayCharges': 75,
      'buildingFund': 1880,
      'roomTransferFees': 0,
      'totalReceivable': 18175,
      'totalReceived': 12015,
      'closingBalance': 6160,
      'fixedMonthlyCharges': 645,
      'annualCharges': 1880,
      'variableCharges': 4275,
    },
    {
      'uid': 'member_19',
      'name': 'S.K. Mallaiya',
      'email': 'skmallaiya@gmail.com',
      'password': 'sk123',
      'phone': '9100000000',
      'flatNumber': '302',
      'role': 'member',
      'status': 'Active',
      'openingBalance': -1213,
      'sinkingFund': 288,
      'maintenanceAmount': 4560,
      'municipalTax': 2388,
      'noc': 3600,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1500,
      'roomTransferFees': 0,
      'totalReceivable': 11123,
      'totalReceived': 9702,
      'closingBalance': 1421,
      'fixedMonthlyCharges': 603,
      'annualCharges': 1500,
      'variableCharges': 3600,
    },
    {
      'uid': 'member_20',
      'name': 'S.M. Patankar',
      'email': 'smpatankar@gmail.com',
      'password': 'sm123',
      'phone': '9100000000',
      'flatNumber': '303',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 3060,
      'sinkingFund': 300,
      'maintenanceAmount': 4560,
      'municipalTax': 2040,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1480,
      'roomTransferFees': 0,
      'totalReceivable': 11440,
      'totalReceived': 6900,
      'closingBalance': 4540,
      'fixedMonthlyCharges': 575,
      'annualCharges': 1480,
      'variableCharges': 0,
    },
    {
      'uid': 'member_21',
      'name': 'M.A. Ramnathkar',
      'email': 'maramnathkar@gmail.com',
      'password': 'ma123',
      'phone': '9100000000',
      'flatNumber': '304',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 3825,
      'sinkingFund': 300,
      'maintenanceAmount': 4560,
      'municipalTax': 2880,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1900,
      'roomTransferFees': 0,
      'totalReceivable': 13465,
      'totalReceived': 7740,
      'closingBalance': 5725,
      'fixedMonthlyCharges': 645,
      'annualCharges': 1900,
      'variableCharges': 0,
    },
    {
      'uid': 'member_22',
      'name': 'A.A. Thakkar',
      'email': 'aathakkar@gmail.com',
      'password': 'aa123',
      'phone': '9100000000',
      'flatNumber': '305',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 4134,
      'sinkingFund': 264,
      'maintenanceAmount': 4560,
      'municipalTax': 1932,
      'noc': 0,
      'parkingCharges': 300,
      'delayCharges': 0,
      'buildingFund': 1360,
      'roomTransferFees': 0,
      'totalReceivable': 12550,
      'totalReceived': 9776,
      'closingBalance': 2774,
      'fixedMonthlyCharges': 563,
      'annualCharges': 1360,
      'variableCharges': 300,
    },
    {
      'uid': 'member_23',
      'name': 'Nirmal A. Darji',
      'email': 'nirmaldarji@gmail.com',
      'password': 'nirmal123',
      'phone': '9100000000',
      'flatNumber': '306',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 2465,
      'sinkingFund': 336,
      'maintenanceAmount': 4560,
      'municipalTax': 3504,
      'noc': 4200,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 2140,
      'roomTransferFees': 0,
      'totalReceivable': 17205,
      'totalReceived': 14740,
      'closingBalance': 2465,
      'fixedMonthlyCharges': 700,
      'annualCharges': 2140,
      'variableCharges': 4200,
    },
    {
      'uid': 'member_24',
      'name': 'H.T. Gawade',
      'email': 'htgawade@gmail.com',
      'password': 'ht123',
      'phone': '9100000000',
      'flatNumber': '401',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 0,
      'sinkingFund': 312,
      'maintenanceAmount': 4560,
      'municipalTax': 2880,
      'noc': 0,
      'parkingCharges': 300,
      'delayCharges': 0,
      'buildingFund': 1880,
      'roomTransferFees': 0,
      'totalReceivable': 9932,
      'totalReceived': 9932,
      'closingBalance': 0,
      'fixedMonthlyCharges': 646,
      'annualCharges': 1880,
      'variableCharges': 300,
    },
    {
      'uid': 'member_25',
      'name': 'Pravin S. Nipunge',
      'email': 'pravinnipunge@gmail.com',
      'password': 'pravin123',
      'phone': '9100000000',
      'flatNumber': '402',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 0,
      'sinkingFund': 288,
      'maintenanceAmount': 4560,
      'municipalTax': 2388,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1500,
      'roomTransferFees': 0,
      'totalReceivable': 8736,
      'totalReceived': 8736,
      'closingBalance': 0,
      'fixedMonthlyCharges': 603,
      'annualCharges': 1500,
      'variableCharges': 0,
    },
    {
      'uid': 'member_26',
      'name': 'Shirish L. Barate',
      'email': 'shirishbarate@gmail.com',
      'password': 'shirish123',
      'phone': '9100000000',
      'flatNumber': '403',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 9080,
      'sinkingFund': 252,
      'maintenanceAmount': 4560,
      'municipalTax': 2040,
      'noc': 3600,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1560,
      'roomTransferFees': 0,
      'totalReceivable': 21092,
      'totalReceived': 6852,
      'closingBalance': 14240,
      'fixedMonthlyCharges': 571,
      'annualCharges': 1560,
      'variableCharges': 3600,
    },
    {
      'uid': 'member_27',
      'name': 'Mangesh Bhosale',
      'email': 'mangeshbhosale@gmail.com',
      'password': 'mangesh123',
      'phone': '9100000000',
      'flatNumber': '404',
      'role': 'member',
      'status': 'Active',
      'openingBalance': -1775,
      'sinkingFund': 372,
      'maintenanceAmount': 4560,
      'municipalTax': 2784,
      'noc': 3150,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1900,
      'roomTransferFees': 25000,
      'totalReceivable': 35991,
      'totalReceived': 10991,
      'closingBalance': 25000,
      'fixedMonthlyCharges': 643,
      'annualCharges': 1900,
      'variableCharges': 28150,
    },
    {
      'uid': 'member_28',
      'name': 'S.S. Gajendragadkar',
      'email': 'ssgajendragadkar@gmail.com',
      'password': 'ss123',
      'phone': '9100000000',
      'flatNumber': '405',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 3300,
      'sinkingFund': 288,
      'maintenanceAmount': 4560,
      'municipalTax': 1932,
      'noc': 3600,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 1360,
      'roomTransferFees': 0,
      'totalReceivable': 15040,
      'totalReceived': 6780,
      'closingBalance': 8260,
      'fixedMonthlyCharges': 565,
      'annualCharges': 1360,
      'variableCharges': 3600,
    },
    {
      'uid': 'member_29',
      'name': 'Sachin R. Mahajan',
      'email': 'sachinmahajan@gmail.com',
      'password': 'sachin123',
      'phone': '9100000000',
      'flatNumber': '406',
      'role': 'member',
      'status': 'Active',
      'openingBalance': 23,
      'sinkingFund': 420,
      'maintenanceAmount': 4560,
      'municipalTax': 3504,
      'noc': 0,
      'parkingCharges': 0,
      'delayCharges': 0,
      'buildingFund': 2140,
      'roomTransferFees': 0,
      'totalReceivable': 10647,
      'totalReceived': 10612,
      'closingBalance': 35,
      'fixedMonthlyCharges': 707,
      'annualCharges': 2140,
      'variableCharges': 0,
    },
  ];
}
